### PR TITLE
AutoRestart Implementation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by maneco2** [comment]
Already happened to me, the server does not connect properly, it is hard to happen, but it happens. (Rarely happens)
And if that happens when you give automatically restart? the server will be offline?

**Comment by Sacrifice78** [comment]
This implementation, I have more than two years ago running. It has not happened to me anything like that before.

**Comment by maneco2** [comment]
This does not happen of implementation, is the Server.

**Comment by maneco2** [comment]
https://cdn.pbrd.co/images/2lwIXQjJ.png
I believe that anyone else has seen this happen.

**Comment by Sacrifice78** [comment]
I have never left me that error.

**Comment by maneco2** [comment]
I've seen many times, I give many restarts on the test server for geodata, so have seen it happen many times. :+1:

**Comment by Sacrifice78** [comment]
It will not be, that must be left a space of time between restarts?. At least 15 minutes between intervals of time according to the default settings. 

Once the reset is made, has 300 seconds and then starts the restart, players data stored in memory are dumped to hard disk and gameserver, which takes about 100 ~ 120 ~ 150 seconds in restart. It takes at least 10 minutes.

**Comment by UnAfraid** [comment]
L2j Supports that by default i don't see a reason for implementing it one more time.
https://github.com/L2J/L2J_Server/blob/master/src/main/java/com/l2jserver/gameserver/taskmanager/tasks/TaskRestart.java

**Comment by Zoey76** [comment]
This can be achieved with one query: https://github.com/L2J/L2J_Server/wiki/Automatic-Server-Restart

**Comment by Sacrifice78** [comment]
Its better with cron task... ;) its true.

**Pull request closed without merging**
