### PR TITLE
Going through the TODO list - part 1

### PR DESCRIPTION
**Pull request by jurchiks**
Next up - FourSepulchersManager with 300+ lines shaved off.

### CODE REVIEW

**Comment by jurchiks** [comment]
It's been 5 days already...

**Comment by jurchiks** [comment]
Let me guess, it's the "you're rude so we're ignoring your contributions" thing again?

**Comment by jurchiks** [comment]
Thanks, @UnAfraid :)

**Comment by Zoey76** [comment]
@jurchiks You are wrong, we talked about this PR with @UnAfraid, we both reviewed it and I told him to merge it and he was waiting for some other PR.

**Comment by jurchiks** [comment]
Well then why didn't you say anything?

**Comment by Zoey76** [comment]
I just forgot, I'll try to keep PRs more updated.

**Pull request merged**
