### PR TITLE
Fixing issue #64

### PR DESCRIPTION
**Pull request by p3110145**
Character doDie should be executed before calculateDeathExpPenalty which reduces karma.
The issue was occuring when karma was small enough that was setting to 0 after calculation and doDie calling onKillUpdatePvPKarma was seeing the target with no karma.

### CODE REVIEW

**Comment by p3110145** [comment]
I hope this permutation won't cause mess to anything else.

**Comment by davion00** [comment]
well this one works.. hope it will not cause more mess to anything else as you said :) thanks

**Comment by Zoey76** [comment]
The code, in current code calls super.doDie(killer) even when killer is null, which won't happen with this change, we must check what happens when killer is null and if we should invoke super.doDie() anyway-

**Comment by p3110145** [comment]
You are right. So it may be better to invoke super.doDie(killer) at the beginning of the function in order to get executed always.

**Comment by p3110145** [comment]
It is for sure faulty cause it leaves out falling damage.

**Comment by Zoey76** [comment]
I think that when killer != null, the if block may perform some check that prevents dying, like listeners or something like that.. maybe the whole logic flow should be changed in order to fix the current bug and keep the rest of the logic.

**Pull request closed without merging**
