### PR TITLE
Typo in Formulas#calcAttributeBonus

### PR DESCRIPTION
**Pull request by luksdlt92**
## Summary

Typo in Formulas#calcAttributeBonus

### CODE REVIEW

**Comment by luksdlt92** [comment]
@Zoey76

**Comment by Zoey76** [comment]
It's a retail typo :sob:

**Comment by luksdlt92** [comment]
@Zoey76 I'm not sure, see the code top and below. It's the only wrong conditional.

**Comment by Zoey76** [comment]
I mean this was already asked and @NosBit said it was retail like, can't find the post.

**Comment by luksdlt92** [comment]
@Zoey76 Mmmm ok :+1:

So, close the PR.

**Comment by Zoey76** [comment]
We could fix it and add a note there, I don't think it's a good idea to leave it like that without any comment.

**Comment by luksdlt92** [comment]
Like 'Retail typo'?

**Comment by luksdlt92** [comment]
@Zoey76 Like this?

**Comment by luksdlt92** [comment]
@Zoey76 Updated

**Pull request merged**
