### PR TITLE
Fix loginserver ertheia Checksum

### PR DESCRIPTION
**Pull request by maneco2**

### CODE REVIEW

**Comment by UnAfraid** [comment]
That is not a fix but hiding a problem.

**Comment by Zoey76** [comment]
What is the problem?

**Comment by maneco2** [comment]
you have not seen? It's impossible to log in, you must always click the server

**Comment by maneco2** [comment]
It's impossible to log in, you must always click the server

**Comment by UnAfraid** [comment]
When using Enter key client sends two packets while click sends one
When there are two checksum falls somehow but it happens with some some IPS for example using 127.0.0.1 might cause it while local host doesn't

**Comment by maneco2** [comment]
yes figured it out, I do not see why remove the log, you are right

**Pull request closed without merging**
