### PR TITLE
Missing condition in the query.

### PR DESCRIPTION
**Pull request by zarie**
Example fix proposed by Digitizer.

### CODE REVIEW

**Comment by zarie** [comment]
@Zoey76 ?

**Comment by u3games** [comment]
up pls ;)

**Comment by Zoey76** [comment]
@u3games instead of "up" you can confirm if the fix work or not :+1:

**Comment by u3games** [comment]
@Zoey76 yes, work ;)

**Comment by zarie** [comment]
"This branch has conflicts that must be resolved" - Updated PR#82 for current branch:
https://github.com/L2J/L2J_Server/pull/196

**Pull request closed without merging**
