### PR TITLE
Sacrifice's Core Updates and/or Implementations

### PR DESCRIPTION
**Pull request by Sacrifice78**

### CODE REVIEW

**Comment by Sacrifice78** [comment]
@Sdwz, Allways we need to add getters and setters like L2J Conventions... I think... no @Zoey76?

**Comment by Sdwz** [comment]
Drop on retail is made in MY_DYING handler in AI (L2J on kill equivalent) not drop list so that's not necessary.

Beside it's done in AI current droplist is wrong.

**Comment by Sacrifice78** [comment]
Im trying to understand whats exactly the problem with implementation... can you iluminate me?.

**Comment by Sdwz** [comment]
You do not have to make a candrop method as treasure doesn't drop as regular monsters. AI makes the treasure chest drop so drop prevention is done there as well

**Comment by Sacrifice78** [comment]
Do you want that I remove this method???... this?...

**Comment by Sdwz** [comment]
L2Attackable changes, yes

**Comment by Sacrifice78** [comment]
Aahhh!!. Now I see it!!... ok. Tomorrow I will revert changes over L2Attackable.java... okok

**Comment by Sacrifice78** [comment]
@Sdwz or @Zoey76
I made a local test what you commented and the result **has not been satisfactory** with the changes you propose. Let me explain step by step:

1.- I removed the two methods and variables created in the file "L2Attackable.java".
2.- As a result, eclipse gives 2 errors in the file "TreasureChests.java" missing the 2 methods previously removed to be invoked.
3.- In the file "TreasureChests.java" I remove calls to those dropped methods.
4.- I recompiled the CORE.
5.- I Replaced the file "TreasureChests.java".
6.- I run LoginServer and GameServer.

**Results:**
In these conditions, I teleported to TreasureChests one by one, and I see that when I attack the chest it explodes, but I get the reward without distinction. According to information available to me... If you attack the chest (with magic or not), it explodes and will generate some damage (proportional to the physical damage that you perform (if you are within the range of action of the explosion)) and chest will disappear until reappearing without drop anything.

This is the information I have available [http://legacy.lineage2.com/news/highfive_04.html] (down (near the end) explains how it works).

Therefore, methods and variables that are introduced in the CORE are necessary to block or not block drop depending on a number of conditions that can be checked in the link I supply.

I say all this because at this moment I do not know if there are other methods in the CORE performing the same.

@Sdwz do you have any other way to do it excluding methods or variables contained in "L2Attackable.java"?.

Pending more reviews...

**Comment by Sdwz** [comment]
Because they shouldn't drop that way.

Current drop are in XML, are wrong and use the regular drop system.

Retail do drops from AI.

**Comment by Sacrifice78** [comment]
But...its possible that anything share his "skills" and finish this feature?, for advanced developers with more experience than me sure that be more easy... umm?

**Comment by Sacrifice78** [comment]
@ivantotov was the last dev that place droplist about chests... take a look of his commit that sumatory of chances of all items in group not plus 100%
https://github.com/L2J/L2J_DataPack/commit/56c1b6b46d6418f804546a9e13170093d8185434

**Comment by Sdwz** [comment]
He took info from a crappy L2OFF pack it's all wrong

**Comment by Sacrifice78** [comment]
Surely... can be fixed?...

**Comment by Sdwz** [comment]
If you can find proper data :D

**Comment by Sacrifice78** [comment]
Now I have an idea for fix droplist of treasure chests... Don't worry, I will do a pull request when I edit and test it...

**Comment by Sacrifice78** [comment]
I created a very rudimentary calculator, which makes the changes from old droplists to new droplist. :+1:

**Comment by Sacrifice78** [comment]
I'm finished!

**Comment by Zealar** [comment]
Remove can drop option rest seems fine.

**Comment by Sacrifice78** [comment]
I will do a local test soon with this changes that you comment. Take in consideration that AI in datapack requiere adaptation also without this options.

**Comment by Zealar** [comment]
Drop for chest need to be removed from npc xml and move in they AI.

**Pull request closed without merging**
