### PR TITLE
Missing condition in Birthday Gift task.

### PR DESCRIPTION
**Pull request by zarie**
Updated PR#82 for current branch.

### CODE REVIEW

**Comment by u3games** [comment]
thx @zarie ^^

**Comment by Sacrifice78** [comment]
Confirmed I received Birthday Gift 3 times in this week.

**Comment by Sacrifice78** [comment]
Query allways return "Empty" for that... never give birthday gift.

**Comment by Sacrifice78** [comment]
I will merge too. Thanks @zarie

**Pull request merged**
